runtime: php55

handlers:
- url: /css
  static_dir: css
  
- url: /images/(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))
  
- url: /.*
  script: main.php